### ISSUE TITLE
Invalid service key undefined, expecting node-service-key

### ISSUE THREAD

**Issue by timdiels1** [beejeebus/drupal-nodejs#43]
Installation:

- Using docker4drupal
- Node version: v8.11.1
- Drupal Core: "drupal/core": "^8.8.2",
- Drupal nodejs module: "drupal/nodejs": "^1.2"

docker-compose info:
```
drupal-node:
    image: wodby/drupal-node:$DRUPAL_NODE_TAG
    container_name: "${PROJECT_NAME}_drupal_nodejs"
    environment:
      NODE_SERVICE_KEY: node-service-key
      NODE_BACKEND_PORT: 8080
      NODE_BACKEND_HOST: drupal-node
      NODE_DEBUG: 1
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_drupal_node.rule=Host(`drupal_node.${PROJECT_BASE_URL}`)"
```

.env info:
```
DRUPAL_NODE_TAG=1.0-2.0.0
```

nodejs.config.yml
```
service_key: node-service-key
resource: /socket.io
log_http_errors: true
auth_get_token_callback: nodejs_auth_get_token_callback
auth_check_callback: nodejs_auth_check_callback
enable_userchannel: true
pages: "/admin/reports/dblog\r\n/auctions\r\n/auctions/*"
authenticated_users_only: false
nodejs:
  scheme: http
  host: drupal-node
  port: '8080'
client:
  scheme: http
  host: ****
  port: '8000'
socket_io:
  path: ''
  type: external
_core:
  default_config_hash: ****

```
nodejs logs:
```
[2020/02/29 11:08:19] Route callback: checkServiceKey
[2020/02/29 11:08:19] checkServiceKey: Invalid service key undefined, expecting node-service-key
[2020/02/29 11:08:19] authenticateClientCallback: Call failed: Invalid service key.
[2020/02/29 11:08:19] cleanupSocket: Cleaning up after socket id gtcOLH4aYBdubCUBAAAp, uid undefined
```

Questions:

- It seems the NodejsServiceKey is not passed to nodejs or nodejs not parsing it orrectly?
- Is there a way to get more debug info like the request.headers in the nodejs application?
- Is there something wrong with the drupal nodejs module?
